language: rust
sudo: true
cache: cargo
rust:
  - 1.34.0
  - stable
  - nightly
os:
  - linux
  - osx
  - windows
env:
  - ARCH=x86_64
  - ARCH=i686
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      :;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install winpcap;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      :;
    fi